### ISSUE TITLE
Coins werden beim Aufruf von sell und anderen Commands verdoppelt

### ISSUE THREAD

**Issue by berbeflo** [Aninoss/Lawliet#1]
https://github.com/Aninoss/Lawliet/blob/6c09b86838f3b8f08a272a24f4fc59ee4ed08382/src/main/java/MySQL/Modules/FisheryUsers/FisheryUserBean.java#L255

In dieser Zeile werden die aktuellen Coins verdoppelt und nicht die Fische verändert.

**Comment by Aninoss** [comment]
Thanks, the issue has been fixed now
