### ISSUE TITLE
Invite Filter: Analyse Shortened Links

### ISSUE THREAD

**Issue by epphy** [Aninoss/Lawliet#64]
Hello there again,

I was checking the invite filter system and spotted out an interesting thing.
It occurs to be that you can bypass the filter by sending a shortened url of 
the original link. 

As for example, I use the service https://shorturl.at/SHvtY for it.
I wonder can it be fixed or not?

![{EEC6F4C7-116C-4198-8C06-372E8C79D56F}](https://github.com/user-attachments/assets/490549d9-de40-47cd-897a-b980894da988)

**Comment by ephyrriz** [comment]
Alrighty, thanks for the answer!
